// Code generated by re2c 2.2 on Mon Jan 03 08:00:14 2022, DO NOT EDIT.
//line "cpp.re":1
package lexers

import (
	"bytes"
    "fmt"
)

const (
	STATE_NORMAL = iota
	STATE_CHARLITERAL
	STATE_STRINGLITERAL
	STATE_RAWSTRINGLITERAL
	STATE_EOLCOMMENT
	STATE_MLCOMMENT
)

func cpp_lex_str(in *Input) TokenType {
	for {
		in.token = in.cursor
    
//line "cpp.go":24
{
	var yych byte
yyFillLabel0:
	yych = peek(in)
	switch (yych) {
	case '"':
		goto yy4
	case '\'':
		goto yy6
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy8
	case '\\':
		goto yy11
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel0
			}
			goto yy34
		}
		goto yy2
	}
yy2:
	in.cursor += 1
yy3:
//line "cpp.re":29
	{ continue }
//line "cpp.go":58
yy4:
	in.cursor += 1
//line "cpp.re":31
	{ if in.state != STATE_STRINGLITERAL { continue }; in.state = STATE_NORMAL; return END }
//line "cpp.go":63
yy6:
	in.cursor += 1
//line "cpp.re":32
	{ if in.state != STATE_CHARLITERAL { continue }; in.state = STATE_NORMAL; return END }
//line "cpp.go":68
yy8:
	in.cursor += 1
yyFillLabel1:
	yych = peek(in)
	switch (yych) {
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy8
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel1
			}
		}
		goto yy10
	}
yy10:
//line "cpp.re":33
	{ return STRINGWORD }
//line "cpp.go":93
yy11:
	in.cursor += 1
yyFillLabel2:
	yych = peek(in)
	switch (yych) {
	case '"':
		goto yy12
	case '\'':
		goto yy14
	case '?':
		goto yy16
	case '\\':
		goto yy18
	case 'a':
		goto yy20
	case 'b':
		goto yy22
	case 'f':
		goto yy24
	case 'n':
		goto yy26
	case 'r':
		goto yy28
	case 't':
		goto yy30
	case 'v':
		goto yy32
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel2
			}
		}
		goto yy3
	}
yy12:
	in.cursor += 1
//line "cpp.re":43
	{ continue }
//line "cpp.go":133
yy14:
	in.cursor += 1
//line "cpp.re":42
	{ continue }
//line "cpp.go":138
yy16:
	in.cursor += 1
//line "cpp.re":44
	{ continue }
//line "cpp.go":143
yy18:
	in.cursor += 1
//line "cpp.re":41
	{ continue }
//line "cpp.go":148
yy20:
	in.cursor += 1
//line "cpp.re":34
	{ continue }
//line "cpp.go":153
yy22:
	in.cursor += 1
//line "cpp.re":35
	{ continue }
//line "cpp.go":158
yy24:
	in.cursor += 1
//line "cpp.re":36
	{ continue }
//line "cpp.go":163
yy26:
	in.cursor += 1
//line "cpp.re":37
	{ continue }
//line "cpp.go":168
yy28:
	in.cursor += 1
//line "cpp.re":38
	{ continue }
//line "cpp.go":173
yy30:
	in.cursor += 1
//line "cpp.re":39
	{ continue }
//line "cpp.go":178
yy32:
	in.cursor += 1
//line "cpp.re":40
	{ continue }
//line "cpp.go":183
yy34:
//line "cpp.re":30
	{ return -1 }
//line "cpp.go":187
}
//line "cpp.re":49

	}
}

func cpp_lex_raw_str(in *Input, start bool) TokenType {
	for {
		if start {
			in.raw_str_delim = in.data[in.token + 2:in.cursor - 1]
			start = false
		}
		in.token = in.cursor
    
//line "cpp.go":202
{
	var yych byte
	yyaccept := 0
yyFillLabel3:
	yych = peek(in)
	switch (yych) {
	case '\n':
		goto yy39
	case ')':
		goto yy41
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy42
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel3
			}
			goto yy51
		}
		goto yy37
	}
yy37:
	in.cursor += 1
yy38:
//line "cpp.re":69
	{ continue }
//line "cpp.go":235
yy39:
	in.cursor += 1
//line "cpp.re":71
	{ in.line += 1; continue }
//line "cpp.go":240
yy41:
	yyaccept = 0
	in.cursor += 1
	in.marker = in.cursor
yyFillLabel4:
	yych = peek(in)
	switch (yych) {
	case '!','"','#':
		fallthrough
	case '%','&':
		fallthrough
	case '*','+',',','-','.','/','0','1','2','3','4','5','6','7','8','9',':',';','<','=','>','?':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','[':
		fallthrough
	case ']','^','_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z','{','|','}','~':
		fallthrough
	case 0x80:
		fallthrough
	case 0x99:
		fallthrough
	case 0xE2:
		goto yy46
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel4
			}
		}
		goto yy38
	}
yy42:
	in.cursor += 1
yyFillLabel5:
	yych = peek(in)
	switch (yych) {
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy42
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel5
			}
		}
		goto yy44
	}
yy44:
//line "cpp.re":79
	{ return STRINGWORD }
//line "cpp.go":298
yy45:
	in.cursor += 1
yyFillLabel6:
	yych = peek(in)
yy46:
	switch (yych) {
	case '!':
		fallthrough
	case '#':
		fallthrough
	case '%','&':
		fallthrough
	case '*','+',',','-','.','/','0','1','2','3','4','5','6','7','8','9',':',';','<','=','>','?':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','[':
		fallthrough
	case ']','^','_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z','{','|','}','~':
		fallthrough
	case 0x80:
		fallthrough
	case 0x99:
		fallthrough
	case 0xE2:
		goto yy45
	case '"':
		goto yy48
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel6
			}
		}
		goto yy47
	}
yy47:
	in.cursor = in.marker
	if (yyaccept == 0) {
		goto yy38
	} else {
		goto yy50
	}
yy48:
	yyaccept = 1
	in.cursor += 1
	in.marker = in.cursor
yyFillLabel7:
	yych = peek(in)
	switch (yych) {
	case '!':
		fallthrough
	case '#':
		fallthrough
	case '%','&':
		fallthrough
	case '*','+',',','-','.','/','0','1','2','3','4','5','6','7','8','9',':',';','<','=','>','?':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','[':
		fallthrough
	case ']','^','_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z','{','|','}','~':
		fallthrough
	case 0x80:
		fallthrough
	case 0x99:
		fallthrough
	case 0xE2:
		goto yy45
	case '"':
		goto yy48
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel7
			}
		}
		goto yy50
	}
yy50:
//line "cpp.re":74
	{ if bytes.Compare(in.raw_str_delim, in.data[in.token+1:in.cursor-1]) != 0 { 
									//fmt.Printf("%s:%d: not end %s\n", in.filename, in.line, in.data[in.token+1:in.cursor-1]); 
									continue
								}
								in.state = STATE_NORMAL; in.raw_str_delim = nil; return END }
//line "cpp.go":386
yy51:
//line "cpp.re":70
	{ return -1 }
//line "cpp.go":390
}
//line "cpp.re":80

	}
}

func cpp_lex_eol_comment(in *Input) TokenType {
	for {
		in.token = in.cursor
    
//line "cpp.go":401
{
	var yych byte
yyFillLabel8:
	yych = peek(in)
	switch (yych) {
	case '\n':
		goto yy56
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy58
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel8
			}
			goto yy61
		}
		goto yy54
	}
yy54:
	in.cursor += 1
//line "cpp.re":96
	{ continue }
//line "cpp.go":430
yy56:
	in.cursor += 1
//line "cpp.re":97
	{ in.state = STATE_NORMAL; in.cursor -= 1; return END }
//line "cpp.go":435
yy58:
	in.cursor += 1
yyFillLabel9:
	yych = peek(in)
	switch (yych) {
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy58
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel9
			}
		}
		goto yy60
	}
yy60:
//line "cpp.re":99
	{ return COMMENTWORD }
//line "cpp.go":460
yy61:
//line "cpp.re":98
	{ return END }
//line "cpp.go":464
}
//line "cpp.re":100

	}
}

func cpp_lex_ml_comment(in *Input) TokenType {
	for {
		in.token = in.cursor
    
//line "cpp.go":475
{
	var yych byte
yyFillLabel10:
	yych = peek(in)
	switch (yych) {
	case '\n':
		goto yy66
	case '*':
		goto yy68
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy69
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel10
			}
			goto yy74
		}
		goto yy64
	}
yy64:
	in.cursor += 1
yy65:
//line "cpp.re":116
	{ continue }
//line "cpp.go":507
yy66:
	in.cursor += 1
//line "cpp.re":117
	{ in.line += 1; continue }
//line "cpp.go":512
yy68:
	in.cursor += 1
yyFillLabel11:
	yych = peek(in)
	switch (yych) {
	case '/':
		goto yy72
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel11
			}
		}
		goto yy65
	}
yy69:
	in.cursor += 1
yyFillLabel12:
	yych = peek(in)
	switch (yych) {
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy69
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel12
			}
		}
		goto yy71
	}
yy71:
//line "cpp.re":120
	{ return COMMENTWORD }
//line "cpp.go":552
yy72:
	in.cursor += 1
//line "cpp.re":118
	{ in.state = STATE_NORMAL; return END }
//line "cpp.go":557
yy74:
//line "cpp.re":119
	{ return END }
//line "cpp.go":561
}
//line "cpp.re":121

	}
}

func cpp_lex(in *Input) TokenType {
	for {
		in.token = in.cursor
        //fmt.Printf("start at %d\n", in.token)
		if in.state == STATE_STRINGLITERAL || in.state == STATE_CHARLITERAL {
			t := cpp_lex_str(in)
			if t >= 0 {
				return t
			}
		} else if (in.state == STATE_RAWSTRINGLITERAL) {
			t := cpp_lex_raw_str(in, false)
			if t >= 0 {
				return t
			}
		} else if (in.state == STATE_EOLCOMMENT) {
			t := cpp_lex_eol_comment(in)
			if t >= 0 {
				return t
			}
		} else if (in.state == STATE_MLCOMMENT) {
			t := cpp_lex_ml_comment(in)
			if t >= 0 {
				return t
			}
		}

	    was_bol := in.bol
		in.bol = false
    
//line "cpp.go":597
{
	var yych byte
	yyaccept := 0
yyFillLabel13:
	yych = peek(in)
	switch (yych) {
	case '\t':
		fallthrough
	case '\v':
		fallthrough
	case '\r':
		fallthrough
	case ' ':
		goto yy79
	case '\n':
		goto yy82
	case '!':
		goto yy84
	case '"':
		goto yy86
	case '#':
		goto yy88
	case '$':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q':
		fallthrough
	case 'S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'e':
		fallthrough
	case 'g','h':
		fallthrough
	case 'j','k':
		fallthrough
	case 'm','n','o','p','q':
		fallthrough
	case 'w','x','y','z':
		goto yy91
	case '%':
		goto yy94
	case '&':
		goto yy96
	case '\'':
		goto yy98
	case '(':
		goto yy100
	case ')':
		goto yy102
	case '*':
		goto yy104
	case '+':
		goto yy106
	case ',':
		goto yy108
	case '-':
		goto yy110
	case '.':
		goto yy112
	case '/':
		goto yy114
	case '0':
		goto yy116
	case '1','2','3','4','5','6','7','8','9':
		goto yy118
	case ':':
		goto yy121
	case ';':
		goto yy123
	case '<':
		goto yy125
	case '=':
		goto yy127
	case '>':
		goto yy129
	case '?':
		goto yy131
	case '@':
		goto yy133
	case 'R':
		goto yy135
	case '[':
		goto yy136
	case '\\':
		goto yy138
	case ']':
		goto yy140
	case '^':
		goto yy142
	case 'a':
		goto yy144
	case 'b':
		goto yy145
	case 'c':
		goto yy146
	case 'd':
		goto yy147
	case 'f':
		goto yy148
	case 'i':
		goto yy149
	case 'l':
		goto yy150
	case 'r':
		goto yy151
	case 's':
		goto yy152
	case 't':
		goto yy153
	case 'u':
		goto yy154
	case 'v':
		goto yy155
	case '{':
		goto yy156
	case '|':
		goto yy158
	case '}':
		goto yy160
	case '~':
		goto yy162
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel13
			}
			goto yy287
		}
		goto yy77
	}
yy77:
	in.cursor += 1
//line "cpp.re":170
	{ fmt.Printf("%s: %d: match %2x\n", in.filename, in.line, in.data[in.cursor-1])); continue }
//line "cpp.go":733
yy79:
	in.cursor += 1
yyFillLabel14:
	yych = peek(in)
	switch (yych) {
	case '\t':
		fallthrough
	case '\v':
		fallthrough
	case '\r':
		fallthrough
	case ' ':
		goto yy79
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel14
			}
		}
		goto yy81
	}
yy81:
//line "cpp.re":167
	{ in.bol = was_bol; continue }
//line "cpp.go":758
yy82:
	in.cursor += 1
//line "cpp.re":168
	{ in.bol = true; in.line += 1; continue }
//line "cpp.go":763
yy84:
	in.cursor += 1
yyFillLabel15:
	yych = peek(in)
	switch (yych) {
	case '=':
		goto yy164
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel15
			}
		}
		goto yy85
	}
yy85:
//line "cpp.re":220
	{ return PUNCTUATION }
//line "cpp.go":782
yy86:
	in.cursor += 1
//line "cpp.re":184
	{ in.state = STATE_STRINGLITERAL; t := cpp_lex_str(in); if t >= 0 { return t }; continue }
//line "cpp.go":787
yy88:
	in.cursor += 1
yyFillLabel16:
	yych = peek(in)
	switch (yych) {
	case '\n':
		goto yy90
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel16
			}
			goto yy90
		}
		goto yy88
	}
yy90:
//line "cpp.re":183
	{ continue }
//line "cpp.go":807
yy91:
	in.cursor += 1
yyFillLabel17:
	yych = peek(in)
yy92:
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy91
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel17
			}
		}
		goto yy93
	}
yy93:
//line "cpp.re":245
	{ return IDENTIFIER }
//line "cpp.go":835
yy94:
	in.cursor += 1
//line "cpp.re":215
	{ return PUNCTUATION }
//line "cpp.go":840
yy96:
	in.cursor += 1
yyFillLabel18:
	yych = peek(in)
	switch (yych) {
	case '&':
		goto yy166
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel18
			}
		}
		goto yy97
	}
yy97:
//line "cpp.re":216
	{ return PUNCTUATION }
//line "cpp.go":859
yy98:
	in.cursor += 1
//line "cpp.re":185
	{ in.state = STATE_CHARLITERAL; t := cpp_lex_str(in); if t >= 0 { return t }; continue }
//line "cpp.go":864
yy100:
	in.cursor += 1
//line "cpp.re":226
	{ return PUNCTUATION }
//line "cpp.go":869
yy102:
	in.cursor += 1
//line "cpp.re":227
	{ return PUNCTUATION }
//line "cpp.go":874
yy104:
	in.cursor += 1
//line "cpp.re":214
	{ return PUNCTUATION }
//line "cpp.go":879
yy106:
	in.cursor += 1
//line "cpp.re":211
	{ return PUNCTUATION }
//line "cpp.go":884
yy108:
	in.cursor += 1
//line "cpp.re":225
	{ return PUNCTUATION }
//line "cpp.go":889
yy110:
	in.cursor += 1
yyFillLabel19:
	yych = peek(in)
	switch (yych) {
	case '>':
		goto yy168
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel19
			}
		}
		goto yy111
	}
yy111:
//line "cpp.re":212
	{ return PUNCTUATION }
//line "cpp.go":908
yy112:
	in.cursor += 1
//line "cpp.re":224
	{ return PUNCTUATION }
//line "cpp.go":913
yy114:
	in.cursor += 1
yyFillLabel20:
	yych = peek(in)
	switch (yych) {
	case '*':
		goto yy170
	case '/':
		goto yy172
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel20
			}
		}
		goto yy115
	}
yy115:
//line "cpp.re":213
	{ return PUNCTUATION }
//line "cpp.go":934
yy116:
	yyaccept = 0
	in.cursor += 1
	in.marker = in.cursor
yyFillLabel21:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel21
			}
		}
		goto yy117
	case 'x':
		goto yy176
	default:
		goto yy175
	}
yy117:
//line "cpp.re":181
	{ return LITERAL }
//line "cpp.go":957
yy118:
	in.cursor += 1
yyFillLabel22:
	yych = peek(in)
	switch (yych) {
	case '0','1','2','3','4','5','6','7','8','9':
		goto yy118
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel22
			}
		}
		goto yy120
	}
yy120:
//line "cpp.re":179
	{ return LITERAL }
//line "cpp.go":976
yy121:
	in.cursor += 1
yyFillLabel23:
	yych = peek(in)
	switch (yych) {
	case ':':
		goto yy178
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel23
			}
		}
		goto yy122
	}
yy122:
//line "cpp.re":241
	{ return PUNCTUATION }
//line "cpp.go":995
yy123:
	in.cursor += 1
//line "cpp.re":223
	{ return PUNCTUATION }
//line "cpp.go":1000
yy125:
	in.cursor += 1
yyFillLabel24:
	yych = peek(in)
	switch (yych) {
	case '=':
		goto yy180
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel24
			}
		}
		goto yy126
	}
yy126:
//line "cpp.re":235
	{ return PUNCTUATION }
//line "cpp.go":1019
yy127:
	in.cursor += 1
yyFillLabel25:
	yych = peek(in)
	switch (yych) {
	case '=':
		goto yy182
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel25
			}
		}
		goto yy128
	}
yy128:
//line "cpp.re":232
	{ return PUNCTUATION }
//line "cpp.go":1038
yy129:
	in.cursor += 1
yyFillLabel26:
	yych = peek(in)
	switch (yych) {
	case '=':
		goto yy184
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel26
			}
		}
		goto yy130
	}
yy130:
//line "cpp.re":236
	{ return PUNCTUATION }
//line "cpp.go":1057
yy131:
	in.cursor += 1
//line "cpp.re":240
	{ return PUNCTUATION }
//line "cpp.go":1062
yy133:
	in.cursor += 1
//line "cpp.re":173
	{ continue }
//line "cpp.go":1067
yy135:
	yyaccept = 1
	in.cursor += 1
	in.marker = in.cursor
yyFillLabel27:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel27
			}
		}
		goto yy93
	case '"':
		goto yy186
	default:
		goto yy92
	}
yy136:
	in.cursor += 1
//line "cpp.re":230
	{ return PUNCTUATION }
//line "cpp.go":1091
yy138:
	in.cursor += 1
//line "cpp.re":166
	{ continue }
//line "cpp.go":1096
yy140:
	in.cursor += 1
//line "cpp.re":231
	{ return PUNCTUATION }
//line "cpp.go":1101
yy142:
	in.cursor += 1
//line "cpp.re":221
	{ return PUNCTUATION }
//line "cpp.go":1106
yy144:
	in.cursor += 1
yyFillLabel28:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel28
			}
		}
		goto yy93
	case 'u':
		goto yy188
	default:
		goto yy92
	}
yy145:
	in.cursor += 1
yyFillLabel29:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel29
			}
		}
		goto yy93
	case 'o':
		goto yy189
	case 'r':
		goto yy190
	default:
		goto yy92
	}
yy146:
	in.cursor += 1
yyFillLabel30:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel30
			}
		}
		goto yy93
	case 'h':
		goto yy191
	case 'o':
		goto yy192
	default:
		goto yy92
	}
yy147:
	in.cursor += 1
yyFillLabel31:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel31
			}
		}
		goto yy93
	case 'o':
		goto yy193
	default:
		goto yy92
	}
yy148:
	in.cursor += 1
yyFillLabel32:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel32
			}
		}
		goto yy93
	case 'o':
		goto yy194
	default:
		goto yy92
	}
yy149:
	in.cursor += 1
yyFillLabel33:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel33
			}
		}
		goto yy93
	case 'f':
		goto yy195
	case 'n':
		goto yy197
	default:
		goto yy92
	}
yy150:
	in.cursor += 1
yyFillLabel34:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel34
			}
		}
		goto yy93
	case 'o':
		goto yy198
	default:
		goto yy92
	}
yy151:
	in.cursor += 1
yyFillLabel35:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel35
			}
		}
		goto yy93
	case 'e':
		goto yy199
	default:
		goto yy92
	}
yy152:
	in.cursor += 1
yyFillLabel36:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel36
			}
		}
		goto yy93
	case 'h':
		goto yy200
	case 'i':
		goto yy201
	case 't':
		goto yy202
	default:
		goto yy92
	}
yy153:
	in.cursor += 1
yyFillLabel37:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel37
			}
		}
		goto yy93
	case 'h':
		goto yy203
	case 'y':
		goto yy204
	default:
		goto yy92
	}
yy154:
	in.cursor += 1
yyFillLabel38:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel38
			}
		}
		goto yy93
	case 'n':
		goto yy205
	default:
		goto yy92
	}
yy155:
	in.cursor += 1
yyFillLabel39:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel39
			}
		}
		goto yy93
	case 'o':
		goto yy206
	default:
		goto yy92
	}
yy156:
	in.cursor += 1
//line "cpp.re":228
	{ return PUNCTUATION }
//line "cpp.go":1327
yy158:
	in.cursor += 1
yyFillLabel40:
	yych = peek(in)
	switch (yych) {
	case '|':
		goto yy207
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel40
			}
		}
		goto yy159
	}
yy159:
//line "cpp.re":217
	{ return PUNCTUATION }
//line "cpp.go":1346
yy160:
	in.cursor += 1
//line "cpp.re":229
	{ return PUNCTUATION }
//line "cpp.go":1351
yy162:
	in.cursor += 1
//line "cpp.re":222
	{ return PUNCTUATION }
//line "cpp.go":1356
yy164:
	in.cursor += 1
//line "cpp.re":234
	{ return PUNCTUATION }
//line "cpp.go":1361
yy166:
	in.cursor += 1
//line "cpp.re":218
	{ return PUNCTUATION }
//line "cpp.go":1366
yy168:
	in.cursor += 1
//line "cpp.re":239
	{ return PUNCTUATION }
//line "cpp.go":1371
yy170:
	in.cursor += 1
//line "cpp.re":189
	{ in.state = STATE_MLCOMMENT; t := cpp_lex_ml_comment(in); if t >= 0 { return t }; continue }
//line "cpp.go":1376
yy172:
	in.cursor += 1
//line "cpp.re":188
	{ in.state = STATE_EOLCOMMENT; t := cpp_lex_eol_comment(in); if t >= 0 { return t }; continue }
//line "cpp.go":1381
yy174:
	in.cursor += 1
yyFillLabel41:
	yych = peek(in)
yy175:
	switch (yych) {
	case '0','1','2','3','4','5','6','7':
		goto yy174
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel41
			}
		}
		goto yy117
	}
yy176:
	in.cursor += 1
yyFillLabel42:
	yych = peek(in)
	switch (yych) {
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F':
		fallthrough
	case 'a','b','c','d','e','f':
		goto yy209
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel42
			}
		}
		goto yy177
	}
yy177:
	in.cursor = in.marker
	if (yyaccept == 0) {
		goto yy117
	} else {
		goto yy93
	}
yy178:
	in.cursor += 1
//line "cpp.re":242
	{ return PUNCTUATION }
//line "cpp.go":1428
yy180:
	in.cursor += 1
//line "cpp.re":237
	{ return PUNCTUATION }
//line "cpp.go":1433
yy182:
	in.cursor += 1
//line "cpp.re":233
	{ return PUNCTUATION }
//line "cpp.go":1438
yy184:
	in.cursor += 1
//line "cpp.re":238
	{ return PUNCTUATION }
//line "cpp.go":1443
yy186:
	in.cursor += 1
yyFillLabel43:
	yych = peek(in)
	switch (yych) {
	case '!','"','#':
		fallthrough
	case '%','&':
		fallthrough
	case '*','+',',','-','.','/','0','1','2','3','4','5','6','7','8','9',':',';','<','=','>','?':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','[':
		fallthrough
	case ']','^','_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z','{','|','}','~':
		fallthrough
	case 0x80:
		fallthrough
	case 0x99:
		fallthrough
	case 0xE2:
		goto yy186
	case '(':
		goto yy212
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel43
			}
		}
		goto yy177
	}
yy188:
	in.cursor += 1
yyFillLabel44:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel44
			}
		}
		goto yy93
	case 't':
		goto yy214
	default:
		goto yy92
	}
yy189:
	in.cursor += 1
yyFillLabel45:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel45
			}
		}
		goto yy93
	case 'o':
		goto yy215
	default:
		goto yy92
	}
yy190:
	in.cursor += 1
yyFillLabel46:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel46
			}
		}
		goto yy93
	case 'e':
		goto yy216
	default:
		goto yy92
	}
yy191:
	in.cursor += 1
yyFillLabel47:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel47
			}
		}
		goto yy93
	case 'a':
		goto yy217
	default:
		goto yy92
	}
yy192:
	in.cursor += 1
yyFillLabel48:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel48
			}
		}
		goto yy93
	case 'n':
		goto yy218
	default:
		goto yy92
	}
yy193:
	in.cursor += 1
yyFillLabel49:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel49
			}
		}
		goto yy93
	case 'u':
		goto yy219
	default:
		goto yy92
	}
yy194:
	in.cursor += 1
yyFillLabel50:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel50
			}
		}
		goto yy93
	case 'r':
		goto yy220
	default:
		goto yy92
	}
yy195:
	in.cursor += 1
yyFillLabel51:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy91
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel51
			}
		}
		goto yy196
	}
yy196:
//line "cpp.re":199
	{ return KEYWORD }
//line "cpp.go":1622
yy197:
	in.cursor += 1
yyFillLabel52:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel52
			}
		}
		goto yy93
	case 't':
		goto yy222
	default:
		goto yy92
	}
yy198:
	in.cursor += 1
yyFillLabel53:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel53
			}
		}
		goto yy93
	case 'n':
		goto yy224
	default:
		goto yy92
	}
yy199:
	in.cursor += 1
yyFillLabel54:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel54
			}
		}
		goto yy93
	case 't':
		goto yy225
	default:
		goto yy92
	}
yy200:
	in.cursor += 1
yyFillLabel55:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel55
			}
		}
		goto yy93
	case 'o':
		goto yy226
	default:
		goto yy92
	}
yy201:
	in.cursor += 1
yyFillLabel56:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel56
			}
		}
		goto yy93
	case 'z':
		goto yy227
	default:
		goto yy92
	}
yy202:
	in.cursor += 1
yyFillLabel57:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel57
			}
		}
		goto yy93
	case 'r':
		goto yy228
	default:
		goto yy92
	}
yy203:
	in.cursor += 1
yyFillLabel58:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel58
			}
		}
		goto yy93
	case 'i':
		goto yy229
	default:
		goto yy92
	}
yy204:
	in.cursor += 1
yyFillLabel59:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel59
			}
		}
		goto yy93
	case 'p':
		goto yy230
	default:
		goto yy92
	}
yy205:
	in.cursor += 1
yyFillLabel60:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel60
			}
		}
		goto yy93
	case 's':
		goto yy231
	default:
		goto yy92
	}
yy206:
	in.cursor += 1
yyFillLabel61:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel61
			}
		}
		goto yy93
	case 'i':
		goto yy232
	default:
		goto yy92
	}
yy207:
	in.cursor += 1
//line "cpp.re":219
	{ return PUNCTUATION }
//line "cpp.go":1797
yy209:
	in.cursor += 1
yyFillLabel62:
	yych = peek(in)
	switch (yych) {
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F':
		fallthrough
	case 'a','b','c','d','e','f':
		goto yy209
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel62
			}
		}
		goto yy211
	}
yy211:
//line "cpp.re":180
	{ return LITERAL }
//line "cpp.go":1820
yy212:
	in.cursor += 1
//line "cpp.re":187
	{ in.state = STATE_RAWSTRINGLITERAL; t := cpp_lex_raw_str(in, true); if t >= 0 { return t }; continue }
//line "cpp.go":1825
yy214:
	in.cursor += 1
yyFillLabel63:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel63
			}
		}
		goto yy93
	case 'o':
		goto yy233
	default:
		goto yy92
	}
yy215:
	in.cursor += 1
yyFillLabel64:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel64
			}
		}
		goto yy93
	case 'l':
		goto yy235
	default:
		goto yy92
	}
yy216:
	in.cursor += 1
yyFillLabel65:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel65
			}
		}
		goto yy93
	case 'a':
		goto yy237
	default:
		goto yy92
	}
yy217:
	in.cursor += 1
yyFillLabel66:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel66
			}
		}
		goto yy93
	case 'r':
		goto yy238
	default:
		goto yy92
	}
yy218:
	in.cursor += 1
yyFillLabel67:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel67
			}
		}
		goto yy93
	case 's':
		goto yy240
	case 't':
		goto yy241
	default:
		goto yy92
	}
yy219:
	in.cursor += 1
yyFillLabel68:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel68
			}
		}
		goto yy93
	case 'b':
		goto yy242
	default:
		goto yy92
	}
yy220:
	in.cursor += 1
yyFillLabel69:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy91
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel69
			}
		}
		goto yy221
	}
yy221:
//line "cpp.re":198
	{ return KEYWORD }
//line "cpp.go":1956
yy222:
	in.cursor += 1
yyFillLabel70:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy91
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel70
			}
		}
		goto yy223
	}
yy223:
//line "cpp.re":200
	{ return KEYWORD }
//line "cpp.go":1983
yy224:
	in.cursor += 1
yyFillLabel71:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel71
			}
		}
		goto yy93
	case 'g':
		goto yy243
	default:
		goto yy92
	}
yy225:
	in.cursor += 1
yyFillLabel72:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel72
			}
		}
		goto yy93
	case 'u':
		goto yy245
	default:
		goto yy92
	}
yy226:
	in.cursor += 1
yyFillLabel73:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel73
			}
		}
		goto yy93
	case 'r':
		goto yy246
	default:
		goto yy92
	}
yy227:
	in.cursor += 1
yyFillLabel74:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel74
			}
		}
		goto yy93
	case 'e':
		goto yy247
	default:
		goto yy92
	}
yy228:
	in.cursor += 1
yyFillLabel75:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel75
			}
		}
		goto yy93
	case 'u':
		goto yy248
	default:
		goto yy92
	}
yy229:
	in.cursor += 1
yyFillLabel76:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel76
			}
		}
		goto yy93
	case 's':
		goto yy249
	default:
		goto yy92
	}
yy230:
	in.cursor += 1
yyFillLabel77:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel77
			}
		}
		goto yy93
	case 'e':
		goto yy251
	default:
		goto yy92
	}
yy231:
	in.cursor += 1
yyFillLabel78:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel78
			}
		}
		goto yy93
	case 'i':
		goto yy252
	default:
		goto yy92
	}
yy232:
	in.cursor += 1
yyFillLabel79:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel79
			}
		}
		goto yy93
	case 'd':
		goto yy253
	default:
		goto yy92
	}
yy233:
	in.cursor += 1
yyFillLabel80:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy91
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel80
			}
		}
		goto yy234
	}
yy234:
//line "cpp.re":191
	{ return KEYWORD }
//line "cpp.go":2163
yy235:
	in.cursor += 1
yyFillLabel81:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy91
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel81
			}
		}
		goto yy236
	}
yy236:
//line "cpp.re":192
	{ return KEYWORD }
//line "cpp.go":2190
yy237:
	in.cursor += 1
yyFillLabel82:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel82
			}
		}
		goto yy93
	case 'k':
		goto yy255
	default:
		goto yy92
	}
yy238:
	in.cursor += 1
yyFillLabel83:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy91
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel83
			}
		}
		goto yy239
	}
yy239:
//line "cpp.re":194
	{ return KEYWORD }
//line "cpp.go":2234
yy240:
	in.cursor += 1
yyFillLabel84:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel84
			}
		}
		goto yy93
	case 't':
		goto yy257
	default:
		goto yy92
	}
yy241:
	in.cursor += 1
yyFillLabel85:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel85
			}
		}
		goto yy93
	case 'i':
		goto yy259
	default:
		goto yy92
	}
yy242:
	in.cursor += 1
yyFillLabel86:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel86
			}
		}
		goto yy93
	case 'l':
		goto yy260
	default:
		goto yy92
	}
yy243:
	in.cursor += 1
yyFillLabel87:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy91
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel87
			}
		}
		goto yy244
	}
yy244:
//line "cpp.re":201
	{ return KEYWORD }
//line "cpp.go":2312
yy245:
	in.cursor += 1
yyFillLabel88:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel88
			}
		}
		goto yy93
	case 'r':
		goto yy261
	default:
		goto yy92
	}
yy246:
	in.cursor += 1
yyFillLabel89:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel89
			}
		}
		goto yy93
	case 't':
		goto yy262
	default:
		goto yy92
	}
yy247:
	in.cursor += 1
yyFillLabel90:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel90
			}
		}
		goto yy93
	case 'o':
		goto yy264
	default:
		goto yy92
	}
yy248:
	in.cursor += 1
yyFillLabel91:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel91
			}
		}
		goto yy93
	case 'c':
		goto yy265
	default:
		goto yy92
	}
yy249:
	in.cursor += 1
yyFillLabel92:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy91
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel92
			}
		}
		goto yy250
	}
yy250:
//line "cpp.re":205
	{ return KEYWORD }
//line "cpp.go":2407
yy251:
	in.cursor += 1
yyFillLabel93:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel93
			}
		}
		goto yy93
	case 'd':
		goto yy266
	default:
		goto yy92
	}
yy252:
	in.cursor += 1
yyFillLabel94:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel94
			}
		}
		goto yy93
	case 'g':
		goto yy267
	default:
		goto yy92
	}
yy253:
	in.cursor += 1
yyFillLabel95:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy91
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel95
			}
		}
		goto yy254
	}
yy254:
//line "cpp.re":209
	{ return KEYWORD }
//line "cpp.go":2468
yy255:
	in.cursor += 1
yyFillLabel96:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy91
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel96
			}
		}
		goto yy256
	}
yy256:
//line "cpp.re":193
	{ return KEYWORD }
//line "cpp.go":2495
yy257:
	in.cursor += 1
yyFillLabel97:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy91
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel97
			}
		}
		goto yy258
	}
yy258:
//line "cpp.re":195
	{ return KEYWORD }
//line "cpp.go":2522
yy259:
	in.cursor += 1
yyFillLabel98:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel98
			}
		}
		goto yy93
	case 'n':
		goto yy268
	default:
		goto yy92
	}
yy260:
	in.cursor += 1
yyFillLabel99:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel99
			}
		}
		goto yy93
	case 'e':
		goto yy269
	default:
		goto yy92
	}
yy261:
	in.cursor += 1
yyFillLabel100:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel100
			}
		}
		goto yy93
	case 'n':
		goto yy271
	default:
		goto yy92
	}
yy262:
	in.cursor += 1
yyFillLabel101:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy91
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel101
			}
		}
		goto yy263
	}
yy263:
//line "cpp.re":202
	{ return KEYWORD }
//line "cpp.go":2600
yy264:
	in.cursor += 1
yyFillLabel102:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel102
			}
		}
		goto yy93
	case 'f':
		goto yy273
	default:
		goto yy92
	}
yy265:
	in.cursor += 1
yyFillLabel103:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel103
			}
		}
		goto yy93
	case 't':
		goto yy275
	default:
		goto yy92
	}
yy266:
	in.cursor += 1
yyFillLabel104:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel104
			}
		}
		goto yy93
	case 'e':
		goto yy277
	default:
		goto yy92
	}
yy267:
	in.cursor += 1
yyFillLabel105:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel105
			}
		}
		goto yy93
	case 'n':
		goto yy278
	default:
		goto yy92
	}
yy268:
	in.cursor += 1
yyFillLabel106:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel106
			}
		}
		goto yy93
	case 'u':
		goto yy279
	default:
		goto yy92
	}
yy269:
	in.cursor += 1
yyFillLabel107:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy91
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel107
			}
		}
		goto yy270
	}
yy270:
//line "cpp.re":197
	{ return KEYWORD }
//line "cpp.go":2712
yy271:
	in.cursor += 1
yyFillLabel108:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy91
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel108
			}
		}
		goto yy272
	}
yy272:
//line "cpp.re":208
	{ return KEYWORD }
//line "cpp.go":2739
yy273:
	in.cursor += 1
yyFillLabel109:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy91
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel109
			}
		}
		goto yy274
	}
yy274:
//line "cpp.re":203
	{ return KEYWORD }
//line "cpp.go":2766
yy275:
	in.cursor += 1
yyFillLabel110:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy91
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel110
			}
		}
		goto yy276
	}
yy276:
//line "cpp.re":204
	{ return KEYWORD }
//line "cpp.go":2793
yy277:
	in.cursor += 1
yyFillLabel111:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel111
			}
		}
		goto yy93
	case 'f':
		goto yy280
	default:
		goto yy92
	}
yy278:
	in.cursor += 1
yyFillLabel112:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel112
			}
		}
		goto yy93
	case 'e':
		goto yy282
	default:
		goto yy92
	}
yy279:
	in.cursor += 1
yyFillLabel113:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel113
			}
		}
		goto yy93
	case 'e':
		goto yy283
	default:
		goto yy92
	}
yy280:
	in.cursor += 1
yyFillLabel114:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy91
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel114
			}
		}
		goto yy281
	}
yy281:
//line "cpp.re":206
	{ return KEYWORD }
//line "cpp.go":2871
yy282:
	in.cursor += 1
yyFillLabel115:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel115
			}
		}
		goto yy93
	case 'd':
		goto yy285
	default:
		goto yy92
	}
yy283:
	in.cursor += 1
yyFillLabel116:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy91
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel116
			}
		}
		goto yy284
	}
yy284:
//line "cpp.re":196
	{ return KEYWORD }
//line "cpp.go":2915
yy285:
	in.cursor += 1
yyFillLabel117:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy91
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel117
			}
		}
		goto yy286
	}
yy286:
//line "cpp.re":207
	{ return KEYWORD }
//line "cpp.go":2942
yy287:
//line "cpp.re":171
	{ return END }
//line "cpp.go":2946
}
//line "cpp.re":246

    }
}
